/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form startScreen
     */
    public WelcomeFrame() {
        initComponents();
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                scaleFonts();
                resizeButton();
            }
        });
    }
    
    private void resizeButton() {
        int baseWidth = 900;
        int baseButtonWidth = 180;
        int baseButtonHeight = 40;
        
        float scale = (float) getWidth() / baseWidth;

        int newW = Math.max(210, Math.round(baseButtonWidth * scale));
        int newH = Math.max(34, Math.round(baseButtonHeight * scale));

        Dimension newSize = new Dimension(newW, newH);

        jButton5.setPreferredSize(newSize);
        jButton5.setMinimumSize(new Dimension(199, 34));
        jButton5.setMaximumSize(new Dimension(400, 100));

        jButton5.revalidate();
        jButton5.getParent().repaint();
    }
    
    private void scaleFonts() {
        float baseWidth = 900f; 
        float scale = getWidth() / baseWidth;
        
        float titleFontSize = Math.max(18f, 15f * scale);
        float bodyFontSize  = Math.max(12f, 13f * scale);
        
        //Home
        float buttonFont = Math.max(18f, 14f * scale);
        float dataAnalysisTitle = Math.max(48f, 29f * scale);
        
        jLabel2.setFont(jLabel2.getFont().deriveFont(dataAnalysisTitle));
        
        jButton5.setFont(jButton5.getFont().deriveFont(buttonFont));
        jLabel14.setFont(jLabel14.getFont().deriveFont(titleFontSize));
        
        jLabel4.setFont(jLabel4.getFont().deriveFont(bodyFontSize));
        jLabel5.setFont(jLabel5.getFont().deriveFont(bodyFontSize));
        jLabel7.setFont(jLabel7.getFont().deriveFont(bodyFontSize));
        jLabel8.setFont(jLabel8.getFont().deriveFont(bodyFontSize));
        jLabel10.setFont(jLabel10.getFont().deriveFont(bodyFontSize));
        jLabel11.setFont(jLabel11.getFont().deriveFont(bodyFontSize));
        //Home
        
        //About us
        jLabel12.setFont(jLabel12.getFont().deriveFont(titleFontSize));
        jLabel13.setFont(jLabel13.getFont().deriveFont(bodyFontSize));
    
        jLabel17.setFont(jLabel17.getFont().deriveFont(titleFontSize));
        jLabel15.setFont(jLabel15.getFont().deriveFont(bodyFontSize));
        //About us
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Analysis Workbench");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(236, 250, 229));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(236, 250, 229));
        jPanel7.setLayout(new java.awt.GridLayout(3, 1));

        jPanel8.setBackground(new java.awt.Color(236, 250, 229));

        jLabel2.setFont(new java.awt.Font("Noto Serif KR", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(176, 219, 156));
        jLabel2.setText("<html>Data Analysis<br/>Workbench</html>");
        jPanel8.add(jLabel2);

        jPanel33.setBackground(new java.awt.Color(236, 250, 229));
        jPanel33.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, -15));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/sistem.png"))); // NOI18N
        jPanel33.add(jLabel1);

        jPanel8.add(jPanel33);

        jPanel7.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(236, 250, 229));
        jPanel9.setLayout(new java.awt.GridLayout(3, 0));

        jPanel14.setBackground(new java.awt.Color(236, 250, 229));

        jButton5.setBackground(new java.awt.Color(202, 232, 189));
        jButton5.setFont(new java.awt.Font("Noto Serif KR", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 188, 133));
        jButton5.setText("Start Data Analyze");
        jButton5.setMaximumSize(null);
        jButton5.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton5.setPreferredSize(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton5);

        jPanel9.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(236, 250, 229));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(236, 250, 229));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jLabel14.setFont(new java.awt.Font("Noto Serif KR", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 188, 133));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("<html>Key Features</html>");
        jLabel14.setPreferredSize(new java.awt.Dimension(500, 50));
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel16.add(jLabel14);

        jPanel9.add(jPanel16);

        jPanel7.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(236, 250, 229));
        jPanel10.setPreferredSize(new java.awt.Dimension(670, 190));
        jPanel10.setLayout(new java.awt.GridLayout(1, 3));

        jPanel11.setBackground(new java.awt.Color(236, 250, 229));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 188, 133), 1, true));
        jPanel11.setLayout(new java.awt.GridLayout(3, 0, 0, -20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/data visual.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 57));
        jPanel11.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Noto Serif KR", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 188, 133));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>Data Visualization</html>");
        jLabel4.setPreferredSize(new java.awt.Dimension(139, 27));
        jPanel11.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Noto Serif KR", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 188, 133));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><center>Create beautiful and informative<br/>charts and graphs effortlessly.</center></html>");
        jPanel11.add(jLabel5);

        jPanel10.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(236, 250, 229));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 188, 133), 1, true));
        jPanel12.setLayout(new java.awt.GridLayout(3, 0, 0, -20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/analytics.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 57));
        jPanel12.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Noto Serif KR", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 188, 133));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>Advanced Analytics</html>");
        jLabel7.setPreferredSize(new java.awt.Dimension(139, 27));
        jPanel12.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Noto Serif KR", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 188, 133));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><center>Utilize a cutting-edge algorithm<br/>for indept data analysis.</center></html>");
        jPanel12.add(jLabel8);

        jPanel10.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(236, 250, 229));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 188, 133), 1, true));
        jPanel13.setLayout(new java.awt.GridLayout(3, 0, 0, -25));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/security.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 57));
        jPanel13.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Noto Serif KR", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 188, 133));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Secure and Reliable");
        jLabel10.setPreferredSize(new java.awt.Dimension(139, 27));
        jPanel13.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Noto Serif KR", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 188, 133));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html><center>Your details are protected  with <br/> industry leading  security measures.</center></html>");
        jPanel13.add(jLabel11);

        jPanel10.add(jPanel13);

        jPanel7.add(jPanel10);

        jPanel2.add(jPanel7, "card3");

        jPanel3.setBackground(new java.awt.Color(236, 250, 229));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(236, 250, 229));
        jPanel17.setPreferredSize(new java.awt.Dimension(663, 50));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jPanel31.setBackground(new java.awt.Color(236, 250, 229));
        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 125, 93)));
        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel12.setFont(new java.awt.Font("Noto Serif KR", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(176, 219, 156));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<html><center>About us</center></html>");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel31.add(jLabel12);

        jPanel17.add(jPanel31);

        jPanel32.setBackground(new java.awt.Color(236, 250, 229));
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 125, 93)));
        jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel17.setFont(new java.awt.Font("Noto Serif KR", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(176, 219, 156));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html><center>Key Features</center></html>");
        jLabel17.setPreferredSize(new java.awt.Dimension(220, 45));
        jPanel32.add(jLabel17);

        jPanel17.add(jPanel32);

        jPanel3.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        jPanel20.setBackground(new java.awt.Color(153, 188, 133));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 125, 93)));
        jPanel20.setPreferredSize(new java.awt.Dimension(663, 150));
        jPanel20.setLayout(new java.awt.GridLayout(3, 0));

        jPanel21.setBackground(new java.awt.Color(153, 188, 133));
        jPanel21.setPreferredSize(new java.awt.Dimension(663, 150));

        jLabel21.setFont(new java.awt.Font("Noto Serif KR", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 250, 229));
        jLabel21.setText("<html>Developed with Java Swing for a cross-platform desktop experience.</html>");
        jLabel21.setPreferredSize(new java.awt.Dimension(500, 21));
        jPanel21.add(jLabel21);

        jPanel20.add(jPanel21);

        jPanel22.setBackground(new java.awt.Color(153, 188, 133));
        jPanel22.setPreferredSize(new java.awt.Dimension(663, 150));

        jLabel22.setBackground(new java.awt.Color(153, 188, 133));
        jLabel22.setFont(new java.awt.Font("Noto Serif KR", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(236, 250, 229));
        jLabel22.setText("<html><center>Version: 1.0<br/>Release Date: May 2025</center></html>");
        jLabel22.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel22.add(jLabel22);

        jPanel20.add(jPanel22);

        jPanel23.setBackground(new java.awt.Color(153, 188, 133));
        jPanel23.setPreferredSize(new java.awt.Dimension(663, 150));
        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 28));

        jLabel23.setFont(new java.awt.Font("Noto Serif KR", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(236, 250, 229));
        jLabel23.setText("<html>© 2025 Jelantronix Tech-tikon. All rights reserved.</html>");
        jLabel23.setPreferredSize(new java.awt.Dimension(370, 21));
        jPanel23.add(jLabel23);

        jPanel20.add(jPanel23);

        jPanel3.add(jPanel20, java.awt.BorderLayout.SOUTH);

        jPanel30.setBackground(new java.awt.Color(236, 250, 229));
        jPanel30.setLayout(new java.awt.GridLayout(2, 0));

        jPanel18.setBackground(new java.awt.Color(236, 250, 229));
        jPanel18.setLayout(new java.awt.GridLayout(1, 2));

        jPanel34.setBackground(new java.awt.Color(153, 188, 133));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 125, 93)));

        jLabel13.setFont(new java.awt.Font("Noto Serif KR", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 250, 229));
        jLabel13.setText("<html>This Data Analysis Software is designed to<br/>provide users with a simple yet powerful<br/>tool for performing basic statistical analysis<br/>and data visualization. It supports common<br/>statistical tests like Z-test, T-test(one-sample<br/>and two-sample), and calculates descriptive<br/>statistics such as mean, median, mode,<br/>and skewness.</html>");
        jPanel34.add(jLabel13);

        jPanel18.add(jPanel34);

        jPanel35.setBackground(new java.awt.Color(153, 188, 133));
        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 125, 93)));

        jLabel15.setFont(new java.awt.Font("Noto Serif KR", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 250, 229));
        jLabel15.setText("<html>-Raw data input and basic statistics<br/>calculation<br/>-One-sample and two-sample T-tests<br/>-One-sample Z-test<br/>-Skewness calculation<br/>-Basic graphical representations<br/>(Histogram, Bar Chart, Scatter Plot)</html>");
        jPanel35.add(jLabel15);

        jPanel18.add(jPanel35);

        jPanel30.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(236, 250, 229));
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 100));

        jLabel16.setText("jLabel16");
        jPanel19.add(jLabel16);

        jPanel30.add(jPanel19);

        jPanel3.add(jPanel30, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, "card2");

        jPanel5.setBackground(new java.awt.Color(236, 250, 229));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, "card3");

        jPanel6.setBackground(new java.awt.Color(236, 250, 229));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, "card3");

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(153, 188, 133));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 188, 133), 5, true));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setPreferredSize(new java.awt.Dimension(663, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel29.setBackground(new java.awt.Color(153, 188, 133));
        jPanel29.setPreferredSize(new java.awt.Dimension(80, 60));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel29, java.awt.BorderLayout.LINE_START);

        jPanel26.setBackground(new java.awt.Color(153, 188, 133));
        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 3));

        jButton1.setBackground(new java.awt.Color(202, 232, 189));
        jButton1.setFont(new java.awt.Font("Noto Serif KR", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 188, 133));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton1);

        jButton2.setBackground(new java.awt.Color(202, 232, 189));
        jButton2.setFont(new java.awt.Font("Noto Serif KR", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 188, 133));
        jButton2.setText("About us");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton2);

        jButton3.setBackground(new java.awt.Color(202, 232, 189));
        jButton3.setFont(new java.awt.Font("Noto Serif KR", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 188, 133));
        jButton3.setText("FAQs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton3);

        jButton4.setBackground(new java.awt.Color(202, 232, 189));
        jButton4.setFont(new java.awt.Font("Noto Serif KR", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 188, 133));
        jButton4.setText("Contact us");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton4);

        jPanel4.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel27.setBackground(new java.awt.Color(153, 188, 133));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel24.setBackground(new java.awt.Color(153, 188, 133));
        jPanel24.setPreferredSize(new java.awt.Dimension(130, 60));
        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jPanel28.setBackground(new java.awt.Color(153, 188, 133));
        jPanel28.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/full_screen_32px.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        jPanel28.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, -1, -1));

        jPanel24.add(jPanel28);

        jPanel25.setBackground(new java.awt.Color(153, 188, 133));
        jPanel25.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });
        jPanel25.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, -1, -1));

        jPanel24.add(jPanel25);

        jPanel27.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel27, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(662, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel2.remove(jPanel3);
        jPanel2.remove(jPanel6);
        jPanel2.remove(jPanel5);
        jPanel2.add(jPanel7);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel2.remove(jPanel7);
        jPanel2.remove(jPanel6);
        jPanel2.remove(jPanel5);
        jPanel2.add(jPanel3);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Mainmenu main = new Mainmenu();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        jPanel25.setBackground(Color.decode("#CAE8BD"));
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        jPanel25.setBackground(Color.decode("#99BC85"));
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        jPanel28.setBackground(Color.decode("#CAE8BD"));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        jPanel28.setBackground(Color.decode("#99BC85"));
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        if (this.getExtendedState() != WelcomeFrame.MAXIMIZED_BOTH) {
            this.setExtendedState(WelcomeFrame.MAXIMIZED_BOTH);
        }
        else {
            this.setExtendedState(WelcomeFrame.NORMAL);
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
